apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gzbkccsn9-nodejs 
  janus-idp.io/tekton: gzbkccsn9-nodejs
  backstage.io/kubernetes-id: gzbkccsn9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gzbkccsn9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  